# Generated by Django 2.0.2 on 2018-06-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=250)),
                ('Last_Name', models.CharField(max_length=250)),
                ('Email', models.EmailField(blank=True, max_length=250, unique=True)),
                ('Contact_Number', models.IntegerField(unique=True)),
                ('Blood_Group', models.CharField(max_length=1)),
                ('Gender', models.CharField(max_length=1)),
                ('Date_of_birth', models.DateField(blank=True)),
                ('Weight', models.IntegerField()),
                ('Address', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Donors',
            },
        ),
    ]
